### ISSUE TITLE
does this is still working now?

### ISSUE THREAD

**Issue by idevz** [khaled0fares/meaning#2]
after install like `sudo gem install meaning`, I found it doesn't work for me.

```bash
 ~/code/z/git/ meaning of Factotum
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/open-uri.rb:225:in `open_loop': redirection forbidden: http://dictionary.cambridge.org/dictionary/english/factotum -> https://dictionary.cambridge.org/dictionary/english/factotum (RuntimeError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/open-uri.rb:151:in `open_uri'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/open-uri.rb:717:in `open'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/open-uri.rb:35:in `open'
	from /Library/Ruby/Gems/2.3.0/gems/meaning-0.1.5/lib/meaning.rb:61:in `file'
	from /Library/Ruby/Gems/2.3.0/gems/meaning-0.1.5/lib/meaning.rb:57:in `load_page'
	from /Library/Ruby/Gems/2.3.0/gems/meaning-0.1.5/lib/meaning.rb:46:in `get_the_content'
	from /Library/Ruby/Gems/2.3.0/gems/meaning-0.1.5/lib/meaning.rb:15:in `define'
	from /Library/Ruby/Gems/2.3.0/gems/meaning-0.1.5/lib/meaning.rb:10:in `initialize'
	from /Library/Ruby/Gems/2.3.0/gems/meaning-0.1.5/bin/meaning:11:in `new'
	from /Library/Ruby/Gems/2.3.0/gems/meaning-0.1.5/bin/meaning:11:in `of'
	from /Library/Ruby/Gems/2.3.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
	from /Library/Ruby/Gems/2.3.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
	from /Library/Ruby/Gems/2.3.0/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
	from /Library/Ruby/Gems/2.3.0/gems/meaning-0.1.5/bin/meaning:49:in `<top (required)>'
	from /usr/local/bin/meaning:22:in `load'
	from /usr/local/bin/meaning:22:in `<main>'
```
does this is still working now?

**Comment by khaled0fares** [comment]
I just tested the CLI and it worked fine on my terminal, Maybe you have an internet connection problem, Could you check it again please?

**Comment by idevz** [comment]
My internet connection is just fine, but I  still have the same Error. 
```bash
 ~/code/z/to-or/ meaning of Factotum
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/open-uri.rb:225:in `open_loop': redirection forbidden: http://dictionary.cambridge.org/dictionary/english/factotum -> https://dictionary.cambridge.org/dictionary/english/factotum (RuntimeError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/open-uri.rb:151:in `open_uri'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/open-uri.rb:717:in `open'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/open-uri.rb:35:in `open'
	from /Library/Ruby/Gems/2.3.0/gems/meaning-0.1.5/lib/meaning.rb:61:in `file'
	from /Library/Ruby/Gems/2.3.0/gems/meaning-0.1.5/lib/meaning.rb:57:in `load_page'
	from /Library/Ruby/Gems/2.3.0/gems/meaning-0.1.5/lib/meaning.rb:46:in `get_the_content'
	from /Library/Ruby/Gems/2.3.0/gems/meaning-0.1.5/lib/meaning.rb:15:in `define'
	from /Library/Ruby/Gems/2.3.0/gems/meaning-0.1.5/lib/meaning.rb:10:in `initialize'
	from /Library/Ruby/Gems/2.3.0/gems/meaning-0.1.5/bin/meaning:11:in `new'
	from /Library/Ruby/Gems/2.3.0/gems/meaning-0.1.5/bin/meaning:11:in `of'
	from /Library/Ruby/Gems/2.3.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
	from /Library/Ruby/Gems/2.3.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
	from /Library/Ruby/Gems/2.3.0/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
	from /Library/Ruby/Gems/2.3.0/gems/meaning-0.1.5/bin/meaning:49:in `<top (required)>'
	from /usr/local/bin/meaning:22:in `load'
	from /usr/local/bin/meaning:22:in `<main>'
 ~/code/z/to-or/ curl -I dictionary.cambridge.org
HTTP/1.1 301 Moved Permanently
Server: nginx
Date: Sun, 15 Jul 2018 23:14:53 GMT
Content-Type: text/html
Content-Length: 178
Connection: keep-alive
Location: https://dictionary.cambridge.org/
```
